# Generated by Django 5.0.1 on 2024-12-14 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_services_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="voyage",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="web_services_project.voyage",
            ),
            preserve_default=False,
        ),
    ]
